version: '3.3'

services:
  mongodb:
    container_name: mongo-book-store
    image: mongo:4.0
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret